name: my_app_viagens
description: Aplicativo Explore Mundo - Agência de Viagens
publish_to: "none" 
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.2.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/praia.png
    - assets/images/montanha.png
    - assets/images/floresta.png
